fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # This one has been added to fail fast on syntax errors
      # before running expensive pylint
      - id: check-ast
        types_or:
          - python
          - pyi
        exclude: "/(site-packages|development-[^/]*|docs|node_modules|__pycache__|\\..*)/$"
      - id: check-yaml
        types: [file]
        files: \.(yaml|yml)$
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/"
        entry: pylint
        args: [-j , "4", --source-roots, .]
      - id: mypy
        name: Local MyPy
        language: system
        types:
          - python
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
#        entry: ./basic-installer.bash mypy --strict
        entry: mypy
        args: [--strict, --show-error-codes, --no-warn-unused-ignores]
# Main problem: python executable path, used to find the environment is hard
#  - repo: https://github.com/pre-commit/mirrors-mypy.git
#    rev: v1.2.0
#    hooks:
#      - id: mypy
#        exclude: "^[^/]*env/|dev-[^/]*/"
#        require_serial: true
#        args: [--strict, --show-error-codes, --no-warn-unused-ignores, --python-executable, .pyWEenv/bin/python]
#  - repo: meta
  - repo: https://github.com/jmfernandez/pre-commit_mirrors-actionlint.git
    rev: v1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/ambv/black.git
    rev: 23.3.0
    hooks:
      - id: black
        name: black_apply
        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        stages: [manual]
      - id: black
        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        args: [--diff, --check]
